# RDC currently only seems to work with the Visual Studio 2017 image
image: Visual Studio 2017

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/
    - /bugfix/.*/

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable --version 5.10.3 -y
  - ps: Install-WindowsFeature -Name "RDC"
  - ps: Get-WindowsFeature -Name "RDC"

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.ArtefactStorage.RavenFS.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.ArtefactStorage.RavenFS.sln

after_build:
  - cmd: nuget pack source\Jobbr.ArtefactStorage.RavenFS.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.ArtefactStorage.RavenFS.%GitVersion_SemVer%.nupkg"

test:
  assemblies:
    - '**\*Jobbr.ArtefactStorage.RavenFS.Tests.dll'

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: anKLNUxe1pn63rrNVCigoQVfA/fWML9gEpE1UHRLK/LDmQX4SM9WwzDx0kliHKWC
  on:
    appveyor_repo_tag: true